### ISSUE TITLE
HDF5 error processing mseeds

### ISSUE THREAD

**Issue by shicks-seismo** [smousavi05/EQTransformer#11]
When running the mseed `preprocessor`, i.e.:
`preprocessor(mseed_dir='mseed/msd', stations_json='station_list.json', overlap=0.3, n_processor=40)` I get the following error:

> Traceback (most recent call last):
  File "3_preprocess_mseed.py", line 4, in <module>
    overlap=0.3, n_processor=40)
  File "/home/shicks17/anaconda3/envs/eqt/lib/python3.7/site-packages/EQTransformer/utils/hdf5_maker.py", line 398, in preprocessor
    p.map(process, station_list)
  File "/home/shicks17/anaconda3/envs/eqt/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/shicks17/anaconda3/envs/eqt/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/home/shicks17/anaconda3/envs/eqt/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/shicks17/anaconda3/envs/eqt/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/shicks17/anaconda3/envs/eqt/lib/python3.7/site-packages/EQTransformer/utils/hdf5_maker.py", line 96, in process
    HDF.create_group("data")
  File "/home/shicks17/anaconda3/envs/eqt/lib/python3.7/site-packages/h5py/_hl/group.py", line 68, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl, gcpl=gcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 161, in h5py.h5g.create
ValueError: Unable to create group (name already exists)
HDF5: infinite loop closing library
      L,T_top,P,P,Z,FD,PL,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E
>
I have tried running both the conda and compile-from-source versions of eqt, but that doesn't solve the error. I am running h5py=2.10.0

**Comment by shicks-seismo** [comment]
Fixed - due to data archive conventions.
