### ISSUE TITLE
Error reading the trained model with h5py

### ISSUE THREAD

**Issue by echavess** [smousavi05/EQTransformer#18]
Hi, 

This is an odd error that is occurring to me on Linux Ubuntu. When I tried to run the predictor I get this error: 

`
Running EqTransformer  0.1.56
 *** Loading the model ...
Traceback (most recent call last):
  File "run_OVtrans.py", line 67, in <module>
    main()
  File "run_OVtrans.py", line 57, in main
    OVT.makePredictor(trained_model='EqT_model.h5')
  File "/home/esteban/Work/EQtrans/C.Pacific/OV_transformer.py", line 94, in makePredictor
    number_of_cpus=10,
  File "/home/esteban/anaconda3/envs/eqt/lib/python3.7/site-packages/EQTransformer/core/predictor.py", line 227, in predictor
    'f1': f1
  File "/home/esteban/anaconda3/envs/eqt/lib/python3.7/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/home/esteban/anaconda3/envs/eqt/lib/python3.7/site-packages/keras/engine/saving.py", line 583, in load_model
    with H5Dict(filepath, mode='r') as h5dict:
  File "/home/esteban/anaconda3/envs/eqt/lib/python3.7/site-packages/keras/utils/io_utils.py", line 191, in __init__
    self.data = h5py.File(path, mode=mode)
  File "/home/esteban/anaconda3/envs/eqt/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/home/esteban/anaconda3/envs/eqt/lib/python3.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (file signature not found)`

If I try to read the h5 file individually, I get the same OSErorr: 

`In [3]: h5py.File("EqT_model.h5", "r")
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-3-bf6c765c3941> in <module>()
----> 1 h5py.File("EqT_model.h5", "r")

/home/esteban/anaconda3/envs/eqt/lib/python3.7/site-packages/h5py/_hl/files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, rdcc_nslots, rdcc_nbytes, rdcc_w0, track_order, **kwds)
    406                 fid = make_fid(name, mode, userblock_size,
    407                                fapl, fcpl=make_fcpl(track_order=track_order),
--> 408                                swmr=swmr)
    409
    410             if isinstance(libver, tuple):

/home/esteban/anaconda3/envs/eqt/lib/python3.7/site-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    171         if swmr and swmr_support:
    172             flags |= h5f.ACC_SWMR_READ
--> 173         fid = h5f.open(name, flags, fapl=fapl)
    174     elif mode == 'r+':
    175         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (file signature not found)`

What's weird, is that, it only shows up when I execute it on a Linux server. On my macbook pro, predictor works just fine. 
I tried updating and downgrading the version of the h5py through anaconda, but didn't work.

**Comment by smousavi05** [comment]
did you try downgrading your TensorFlow or Keras version as well? Sometimes similar things happen that will be fixed by only reinstalling the TensorFLow.

**Comment by echavess** [comment]
Will try this a let you know.
