### ISSUE TITLE
Error in running the example

### ISSUE THREAD

**Issue by wangliang1989** [smousavi05/EQTransformer#29]
Platform: mac OS 11.1 & python3.7

I follow the readme of master branch to install the EQT (with conda).
Then I try to run the example in the tutorial: https://eqtransformer.readthedocs.io/en/latest/tutorial.html

But, I find two errors when using the predictor.

The first one is that:

````
>>> predictor(input_dir= 'downloads_mseeds_processed_hdfs', input_model='EqT_model.h5', output_dir='detections', detection_threshold=0.3, P_threshold=0.1, S_threshold=0.1, number_of_plots=100, plot_mode='time')
============================================================================
Running EqTransformer  0.1.56
 *** Loading the model ...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/liang/local/anaconda3/envs/eqt/lib/python3.7/site-packages/EQTransformer/core/predictor.py", line 227, in predictor
    'f1': f1
  File "/Users/liang/local/anaconda3/envs/eqt/lib/python3.7/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/Users/liang/local/anaconda3/envs/eqt/lib/python3.7/site-packages/keras/engine/saving.py", line 583, in load_model
    with H5Dict(filepath, mode='r') as h5dict:
  File "/Users/liang/local/anaconda3/envs/eqt/lib/python3.7/site-packages/keras/utils/io_utils.py", line 191, in __init__
    self.data = h5py.File(path, mode=mode)
  File "/Users/liang/local/anaconda3/envs/eqt/lib/python3.7/site-packages/h5py/_hl/files.py", line 427, in __init__
    swmr=swmr)
  File "/Users/liang/local/anaconda3/envs/eqt/lib/python3.7/site-packages/h5py/_hl/files.py", line 190, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'EqT_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
````

I fix this by myself, but I cannot solve the the second one:

````
>>> predictor(input_dir= 'downloads_mseeds_processed_hdfs', input_model='EQTransformer/ModelsAndSampleData/EqT_model.h5', output_dir='detections', detection_threshold=0.3, P_threshold=0.1, S_threshold=0.1, number_of_plots=100, plot_mode='time')
============================================================================
Running EqTransformer  0.1.56
 *** Loading the model ...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/liang/local/anaconda3/envs/eqt/lib/python3.7/site-packages/EQTransformer/core/predictor.py", line 227, in predictor
    'f1': f1
  File "/Users/liang/local/anaconda3/envs/eqt/lib/python3.7/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/Users/liang/local/anaconda3/envs/eqt/lib/python3.7/site-packages/keras/engine/saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "/Users/liang/local/anaconda3/envs/eqt/lib/python3.7/site-packages/keras/engine/saving.py", line 273, in _deserialize_model
    model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
````

**Comment by smousavi05** [comment]
@wangliang1989 

Just downgraded h5py to 2.10.0 version:

python -m pip uninstall h5py
pip install h5py==2.10.0

**Comment by wangliang1989** [comment]
> @wangliang1989
> 
> Just downgraded h5py to 2.10.0 version:
> 
> python -m pip uninstall h5py
> pip install h5py==2.10.0

I install the EQT by conda. Are you sure that I should use pip to install something?
I am new in python

**Comment by smousavi05** [comment]
Yes, just use those lines in my previous comment to replace h5py in your current anaconda.

**Comment by wangliang1989** [comment]
I have tried, below is also needed:
pip install jupyter
and I got this:
![image](https://user-images.githubusercontent.com/12059719/105323190-d0f0d200-5c04-11eb-9289-efe1c51d7fd5.png)
My English is not very well, please forgive me.

**Comment by smousavi05** [comment]
Right, to run the examples you need to download the files inside ModelAndSampleData folder in GitHub page. Please also read the Tutorial carefully. All of these have been mentioned there.

**Comment by wangliang1989** [comment]
> @wangliang1989
> 
> Just downgraded h5py to 2.10.0 version:
> 
> python -m pip uninstall h5py
> pip install h5py==2.10.0

Why not add this into the INSTALLATION of the README file?
