### ISSUE TITLE
"unable to open file: name = 'EqT_model.h5'", but I have h5py==2.10.0

### ISSUE THREAD

**Issue by Bryanrt-geophys** [smousavi05/EQTransformer#37]
Sorry for the long post, but I figured more information was better than too little. I listed all of my environments packages at the end. 

While working through the tutorial, I have reached the point where the predictor() function is called for the first option of detecting and picking. 

```
from EQTransformer.core.predictor import predictor

predictor(input_dir= 'downloads_mseeds_processed_hdfs', input_model='EqT_model.h5', output_dir='detections', detection_threshold=0.3, P_threshold=0.1, S_threshold=0.1, number_of_plots=100, plot_mode='time')
```

When I run this function, I receive this error:

```
: predictor(input_dir= 'downloads_mseeds_processed_hdfs', 
          input_model='EqT_model.h5', 
          output_dir='detections', 
          detection_threshold=0.3, 
          P_threshold=0.1, 
          S_threshold=0.1, 
          number_of_plots=100, 
          plot_mode='time')
============================================================================
Running EqTransformer  0.1.59
 *** Loading the model ...
Traceback (most recent call last):

  File "<ipython-input-7-e1b33207579b>", line 8, in <module>
    plot_mode='time')

  File "/Users/camithomas/opt/anaconda3/envs/eqt/lib/python3.7/site-packages/EQTransformer/core/predictor.py", line 233, in predictor
    'f1': f1

  File "/Users/camithomas/opt/anaconda3/envs/eqt/lib/python3.7/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)

  File "/Users/camithomas/opt/anaconda3/envs/eqt/lib/python3.7/site-packages/keras/engine/saving.py", line 583, in load_model
    with H5Dict(filepath, mode='r') as h5dict:

  File "/Users/camithomas/opt/anaconda3/envs/eqt/lib/python3.7/site-packages/keras/utils/io_utils.py", line 191, in __init__
    self.data = h5py.File(path, mode=mode)

  File "/Users/camithomas/opt/anaconda3/envs/eqt/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)

  File "/Users/camithomas/opt/anaconda3/envs/eqt/lib/python3.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)

  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

  File "h5py/h5f.pyx", line 88, in h5py.h5f.open

OSError: Unable to open file (unable to open file: name = 'EqT_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```

From other Issues posts, I had assumed this was a result of h5py needing to be downgraded but I checked my version and it seems to match the suggested h5py==2.10.0.  Any suggestions? When I checked the downloads_mseeds_processed_hdfs folder, there was no EqT_model.h5. Should this model be created and populated in this directory automatically, or do I need to grab this model from a different directory?

Running package versions:
```
pip list
Package                       Version
----------------------------- -------------------
absl-py                       0.11.0
alabaster                     0.7.12
appdirs                       1.4.4
applaunchservices             0.2.1
appnope                       0.1.2
argh                          0.26.2
argon2-cffi                   20.1.0
astor                         0.8.1
astroid                       2.4.2
astunparse                    1.6.3
async-generator               1.10
atomicwrites                  1.4.0
attrs                         20.3.0
autopep8                      1.5.4
Babel                         2.9.0
backcall                      0.2.0
black                         19.10b0
bleach                        3.2.3
brotlipy                      0.7.0
cachetools                    4.2.1
certifi                       2020.12.5
cffi                          1.14.4
chardet                       4.0.0
click                         7.1.2
cloudpickle                   1.6.0
colorama                      0.4.4
cryptography                  3.3.1
cycler                        0.10.0
decorator                     4.4.2
defusedxml                    0.6.0
diff-match-patch              20200713
docutils                      0.16
entrypoints                   0.3
EQTransformer                 0.1.59
flake8                        3.8.4
flatbuffers                   1.12
future                        0.18.2
gast                          0.2.2
google-auth                   1.24.0
google-auth-oauthlib          0.4.2
google-pasta                  0.2.0
grpcio                        1.32.0
h5py                          2.10.0
idna                          2.10
imagesize                     1.2.0
importlib-metadata            3.4.0
iniconfig                     1.1.1
intervaltree                  3.1.0
ipykernel                     5.4.3
ipython                       7.19.0
ipython-genutils              0.2.0
ipywidgets                    7.6.3
isort                         5.6.4
jedi                          0.18.0
Jinja2                        2.11.2
jsonschema                    3.2.0
jupyter                       1.0.0
jupyter-client                6.1.11
jupyter-console               6.2.0
jupyter-core                  4.7.0
jupyterlab-pygments           0.1.2
jupyterlab-widgets            1.0.0
Keras                         2.3.1
Keras-Applications            1.0.8
Keras-Preprocessing           1.1.2
keyring                       22.0.1
kiwisolver                    1.3.1
lazy-object-proxy             1.4.3
lxml                          4.6.2
Markdown                      3.3.3
MarkupSafe                    1.1.1
matplotlib                    3.3.4
mccabe                        0.6.1
mistune                       0.8.4
mypy-extensions               0.4.3
nbclient                      0.5.1
nbconvert                     6.0.7
nbformat                      5.1.2
nest-asyncio                  1.5.1
notebook                      6.2.0
numpy                         1.19.5
numpydoc                      1.1.0
oauthlib                      3.1.0
obspy                         1.2.2
opt-einsum                    3.3.0
packaging                     20.8
pandas                        1.2.1
pandocfilters                 1.4.3
parso                         0.8.1
pathspec                      0.7.0
pathtools                     0.1.2
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        8.1.0
pip                           20.3.3
pkginfo                       1.7.0
pluggy                        0.13.1
prometheus-client             0.9.0
prompt-toolkit                3.0.14
protobuf                      3.14.0
psutil                        5.7.2
ptyprocess                    0.7.0
py                            1.10.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycodestyle                   2.6.0
pycparser                     2.20
pydocstyle                    5.1.1
pyflakes                      2.2.0
Pygments                      2.7.4
pylint                        2.6.0
pyls-black                    0.4.6
pyls-spyder                   0.3.0
pyOpenSSL                     20.0.1
pyparsing                     2.4.7
pyrsistent                    0.17.3
PySocks                       1.7.1
pytest                        6.2.2
python-dateutil               2.8.1
python-jsonrpc-server         0.4.0
python-language-server        0.36.2
pytz                          2020.5
PyYAML                        5.4.1
pyzmq                         22.0.0
QDarkStyle                    2.8.1
QtAwesome                     1.0.1
qtconsole                     5.0.2
QtPy                          1.9.0
regex                         2020.11.13
requests                      2.25.1
requests-oauthlib             1.3.0
rope                          0.18.0
rsa                           4.7
Rtree                         0.9.4
scipy                         1.4.1
Send2Trash                    1.5.0
setuptools                    52.0.0.post20210125
six                           1.15.0
snowballstemmer               2.1.0
sortedcontainers              2.3.0
Sphinx                        3.4.3
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
spyder                        4.2.0
spyder-kernels                1.10.1
SQLAlchemy                    1.3.22
tensorboard                   2.0.2
tensorboard-plugin-wit        1.8.0
tensorflow                    2.0.0
tensorflow-estimator          2.0.1
termcolor                     1.1.0
terminado                     0.9.2
testpath                      0.4.4
three-merge                   0.1.1
toml                          0.10.2
tornado                       6.1
tqdm                          4.48.0
traitlets                     5.0.5
typed-ast                     1.4.2
typing-extensions             3.7.4.3
ujson                         4.0.2
urllib3                       1.26.3
watchdog                      0.10.4
wcwidth                       0.2.5
webencodings                  0.5.1
Werkzeug                      1.0.1
wheel                         0.36.2
widgetsnbextension            3.5.1
wrapt                         1.12.1
wurlitzer                     2.0.1
yapf                          0.30.0
zipp                          3.4.0
```

**Comment by smousavi05** [comment]
@Bryanrt-geophys don't worry everythings looks good. You just need to download the model (EqT_model.h5) from [here](https://github.com/smousavi05/EQTransformer/tree/master/ModelsAndSampleData) and put it in the same directory from which you are running your Jupyter Notebook or change the address to it (input_model='EqT_model.h5').

**Comment by Bryanrt-geophys** [comment]
Thank you kindly for the great tool and assistance. This fixed my issue but I have three minor comments/questions:

1. I modified the argument to pass the path to the file. I did notice at a few other spots in the tutorial the provided code assumed certain files where in the cwd even though they were created elsewhere. In these cases I also changed the arguments to the necessary paths. I don't know if this is important enough to be adjusted on the documentation, but if so I can provide the places where this was the case. 

2. Both in the documentation and in the code a file is created called traceNmae_dic.json. Not sure if this was intentional spelling or if you wan't to adjust it to traceName_dic.json. There also is a minor spelling discrepancy between your function run_associator(), the file associations.xml, and the directory asociation.   

3. This is probably much more of an issue with me not being fully familiar with python and python IDE's like Spyder (what I have been running everything out of). When attempt to use plot_helicorder() to check the sensitivity of the chosen thresholds, no plots are automatically generated unless I add save_plot=True to the arguments. However, it appears these plots have the same names as the highlighted plot overwrites the unhighlighted plot. This also saves the plots in the cwd. Can each plot be set to have their names unique? If so, would you suggest feeding the two plot_helicorder() lines into loop that saves the plots in their respective station_outputs folder within the detections folder? 

I'm about to move on to step 3.5 Building and Testing a New Model. I am super impressed with the tool thus far and have greatly appreciated the effective issues responses. I'm sure I will have other questions as I get deeper into your work. Thanks again!

**Comment by smousavi05** [comment]
Hi @Bryanrt-geophys thanks for pointing out those typos. I'll try to fix them in the next update. 
For your question on the plotting, the helicorder plot names are set to be the same as the miniseed file name. The highlighted ones are intentionally set to have the same name to prevent too much mess. You can easily write a loop to read all the mseed files in a folder and plot them but that might not be necessary as there might be thousands of miniseed files or they might be much longer than a day long. Those plotting routines are only for a fast diagnosis and double checking a few sample files to get some feeling that if everything works fine or not. Let me know if you had other questions. 
Mostafa

**Comment by Pragnath** [comment]
i too have the same issue it is working in jupyter notebook but in google colab  the  error is not fixed even though i have mentioned the working directory



**from EQTransformer.core.predictor import predictor

predictor(input_dir= 'downloads_mseeds_processed_hdfs', input_model='/home/pragnath/EQTransformer/EqT_model.h5', output_dir='detections1', detection_threshold=0.3, P_threshold=0.1, S_threshold=0.1, number_of_plots=100, plot_mode='time')**



**OSError: Unable to open file (unable to open file: name = 'EqT_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)**
