### ISSUE TITLE
i wanted to use local mseed data，but ValueError: not enough values to unpack (expected 3, got 0)

### ISSUE THREAD

**Issue by spaopaos** [smousavi05/EQTransformer#91]
Hello Mustafa,when running detections (from local mseeds) I get the following error

from EQTransformer.utils.hdf5_maker import stationListFromMseed
mseed_directory = '/home/spaopaos/PycharmProjects/pythonProject5/downloads_mseeds'
station_locations = {"BHC": [36.84330, 121.66770, 44.4], "LOK": [36.84490, 121.65170, 2.4], "RSH": [36.87690, 121.63990, 31.5]}
stationListFromMseed(mseed_directory, station_locations)
import os
json_basepath = os.path.join(os.getcwd(),"station_list.json")
from EQTransformer.core.mseed_predictor import mseed_predictor
mseed_predictor(input_dir='downloads_mseeds',
         input_model='EqT_model2.h5',
         stations_json=json_basepath,
         output_dir='detections2',
         loss_weights=[0.02, 0.40, 0.58],
         detection_threshold=0.3,
         P_threshold=0.1,
         S_threshold=0.1,
         number_of_plots=10,
         plot_mode='time_frequency',
         normalization_mode='std',
         batch_size=500,
         overlap=0.3,
         gpuid=None,
         gpu_limit=None)

Using TensorFlow backend.
09-25 20:15 [INFO] [EQTransformer] Running EqTransformer  0.1.59
09-25 20:15 [INFO] [EQTransformer] *** Loading the model ...
2021-09-25 20:15:12.940793: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2021-09-25 20:15:12.943321: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 4194000000 Hz
2021-09-25 20:15:12.943427: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x564409ad20f0 executing computations on platform Host. Devices:
2021-09-25 20:15:12.943448: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
09-25 20:15 [INFO] [EQTransformer] *** Loading is complete!
09-25 20:15 [INFO] [EQTransformer] There are files for 3 stations in downloads_mseeds directory.
09-25 20:15 [INFO] [EQTransformer] Started working on BHC, 1 out of 3 ...
09-25 20:15 [INFO] [EQTransformer] 20140902T000000Z__20140902T010000Z.mseed
Traceback (most recent call last):
  File "/home/spaopaos/miniconda3/envs/eqt/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-4101989e935b>", line 1, in <module>
    runfile('/home/spaopaos/PycharmProjects/pythonProject5/main.py', wdir='/home/spaopaos/PycharmProjects/pythonProject5')
  File "/snap/pycharm-community/252/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/snap/pycharm-community/252/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/spaopaos/PycharmProjects/pythonProject5/main.py", line 23, in <module>
    gpu_limit=None)
  File "/home/spaopaos/miniconda3/envs/eqt/lib/python3.7/site-packages/EQTransformer/core/mseed_predictor.py", line 311, in mseed_predictor
    predD, predP, predS = model.predict_generator(pred_generator)
ValueError: not enough values to unpack (expected 3, got 0)

**Comment by smousavi05** [comment]
@spaopaos How about the examples? were you able to run the examples successfully? I recommend to first run the examples and then check the prepared data and list of your local mseeds using  stationListFromMseed. It seems the model did not produce any output prediction. In these type of cases, I would first check the data (i.e. if the mseed files contain good waveforms with at least 1 hour long) and then double check the outputs of the stationListFromMseed. However, before this you need to first check if the code runs properly on the example data so there are no installation/dependent packages issues.

**Comment by spaopaos** [comment]
I have been able to run the example successfully.I can guarantee that there are no installation packages issues.However, when I use local mseed datas, the terminal will show:ValueError: not enough values to unpack (expected 3, got 0)
  My mseed datas is 100Hz sampling rate and 1 hour long.There's a strange question that When I put the data downloaded from iris into the station folder,it works well,But not when I use my own data.I want to know if EQT has any requirements for the format of mseed datas(Because my datas' encoding is float32 but example is STEIM2)

**Comment by smousavi05** [comment]
@spaopaos the conversion code for local mseed data is a contribution of other people to the EqT package. I did not write it so can not comment on it. It just makes station_list.json file based on the mseed files. My suspicion is that your mseed files either do not have the appropriate file naming format or they do not contains metadata info such as station lat/long, sampling rates, etc. So I would say to first try to read in your mseed files using Obspy and look at the header fields (trace meta data info). They should have similar info as those downloaded from IRIS.

**Comment by spaopaos** [comment]
That's OK. Thank you very much! The station ID in the metadata is a little different from that downloaded from iris. It can run normally after I modify it
